---
# roles/example/tasks/main.yml
# - name: Install the correct web server for RHEL
#   ansible.builtin.import_tasks: redhat.yml
#   when: ansible_facts['os_family']|lower == 'redhat'
#   import_tasks: redhat.yml
#   when: ansible_facts['os_family']|lower == 'redhat'

# - name: Install the correct web server for Debian
#   import_tasks: debian.yml
#   when: ansible_facts['os_family']|lower == 'debian'

# install web server on ubuntu
- name: Install web server
  ansible.builtin.apt:
    name: "apache2"
    state: present

# roles/example/tasks/redhat.yml
- name: Install web server
  ansible.builtin.yum:
    name: "httpd"
    state: present

# roles/example/tasks/debian.yml
- name: Install web server
  ansible.builtin.apt:
    name: "apache2"
    state: present
