# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: conan-kind-cluter
nodes:
- role: control-plane
- role: worker
- role: worker
metadata:
  name: custom-namespace
  labels:
    custom-label: "true"
  annotations:
    custom-annotation: "true"